model:
  input_shape: 8
  output_shape: 1
  layers:
    - type: "dense"
      neurons: 2048
      activation: "relu"    
    - type: "dense"
      neurons: 2048
      activation: "relu"    
    - type: "dense"
      neurons: 2048
      activation: "relu"    
    - type: "dense"
      neurons: 2048
      activation: "relu"    
    - type: "dense"
      neurons: 2048
      activation: "relu"

training:
  batch_size: 8192
  optimizer: "adam"
  learning_rate: 1e-6
  regularization: 1e-7
  loss_function: "binary_crossentropy"
  input_features: [
    'pt_H',
    'lep_phi0_1',
    'met', 
    'lep_pt_1',
    'N_j_central',
    'Dphi_metyy',
    'y1_phi0',
    'y1_eta'
  ]
  
EarlyStopping:
  patience: 5
  rise_delta: 1e-5
  threshold_delta: 1e-4
  
data:
  train_dataset: "/path/to/train_data.csv"
  validation_dataset: "/path/to/validation_data.csv"
  test_dataset: "/path/to/test_data.csv"
  target_column: "label"

logging:
  log_dir: "/path/to/logs"
  save_model: true
  model_save_path: "/path/to/saved_model.h5"